#!/bin/bash
# SPDX-License-Identifier: CC0-1.0
# Setup GPG pinentry for non-blocking password input
# Usage: setup-gpg-pinentry.sh [--auto | --gtk2 | --gnome3 | --qt]

set -e

# Color codes for output
readonly RED='\033[0;31m'
readonly GREEN='\033[0;32m'
readonly YELLOW='\033[1;33m'
readonly NC='\033[0m' # No Color

log_info() {
    printf "${GREEN}[✓]${NC} %s\n" "$@" >&2
}

log_warn() {
    printf "${YELLOW}[!]${NC} %s\n" "$@" >&2
}

log_error() {
    printf "${RED}[✗]${NC} %s\n" "$@" >&2
}

usage() {
    cat >&2 <<'EOF'
Usage: setup-gpg-pinentry.sh [--auto | --gtk2 | --gnome3 | --qt | --kde]

Options:
  --auto      Automatically detect and use the best available pinentry
  --gtk2      Use pinentry-gtk2 (recommended, most compatible)
  --gnome3    Use pinentry-gnome3 (best for GNOME/Wayland)
  --qt        Use pinentry-qt (KDE/Qt environments)
  --kde       Use pinentry-kde (KDE specific)
  --help      Show this help message

Examples:
  setup-gpg-pinentry.sh                # Auto-detect
  setup-gpg-pinentry.sh --gtk2         # Force GTK2
  setup-gpg-pinentry.sh --gnome3       # Force GNOME3

EOF
}

# Find available pinentry program
# Skips candidates that exist but fail to execute (e.g. missing shared
# libraries such as gcr for pinentry-gnome3 or kwindowsystem for pinentry-qt).
find_pinentry() {
    local -a candidates=(
        "pinentry-gnome3"    # GNOME, excellent Wayland support
        "pinentry-gtk2"      # GTK2, most universal
        "pinentry-qt"        # Qt-based
        "pinentry-kde"       # KDE specific
        "pinentry-curses"    # Non-blocking terminal (fallback)
    )
    
    for prog in "${candidates[@]}"; do
        local path
        path=$(command -v "$prog" 2>/dev/null) || continue
        if "$path" --version >/dev/null 2>&1; then
            echo "$prog"
            return 0
        else
            log_warn "$prog found but failed to run (missing dependency?), skipping"
        fi
    done
    
    return 1
}

# Get the full path to a pinentry program
get_pinentry_path() {
    local prog="$1"
    
    if [[ "$prog" == "pinentry-"* ]]; then
        command -v "$prog" 2>/dev/null || echo ""
    else
        echo ""
    fi
}

# Verify system supports GUI pinentry
check_gui_support() {
    if [[ -z "$DISPLAY" ]] && [[ -z "$WAYLAND_DISPLAY" ]]; then
        log_warn "No X11 or Wayland detected. GUI pinentry may not work."
        log_warn "Consider using pinentry-curses or pinentry-tty instead."
        return 1
    fi
    return 0
}

# Check if pinentry is installed
check_pinentry_installed() {
    local pinentry="$1"
    
    if [[ ! -x "$pinentry" ]]; then
        log_error "Pinentry program not found: $pinentry"
        return 1
    fi

    # Verify it actually runs (catches missing shared-library dependencies,
    # e.g. pinentry-gnome3 needs gcr, pinentry-qt needs kwindowsystem)
    if ! "$pinentry" --version >/dev/null 2>&1; then
        log_error "Pinentry program failed to run: $pinentry"
        log_error "It is likely missing a shared-library dependency. Run:"
        log_error "  $pinentry --version"
        log_error "to see the missing library, then install its package."
        return 1
    fi
    return 0
}

# Configure gpg-agent.conf
configure_gpg_agent() {
    local pinentry_path="$1"
    local gpg_agent_config="$HOME/.gnupg/gpg-agent.conf"
    
    log_info "Configuring GPG agent at $gpg_agent_config"
    
    # Create directory structure
    mkdir -p "$(dirname "$gpg_agent_config")"
    chmod 700 "$(dirname "$gpg_agent_config")"
    
    # Write configuration
    {
        echo "# GPG Agent Configuration"
        echo "# Generated by setup-gpg-pinentry.sh"
        echo ""
        echo "# Pinentry program for password entry (GUI, non-blocking)"
        echo "pinentry-program $pinentry_path"
        echo ""
        echo "# Cache settings (9.6 hours = 34560 seconds)"
        echo "max-cache-ttl 34560"
        echo "default-cache-ttl 34560"
        echo ""
        echo "# SSH key support (useful for Pi workflows)"
        echo "enable-ssh-support"
        echo ""
        echo "# Allow loopback pinentry (for scripts/testing)"
        echo "allow-loopback-pinentry"
        echo ""
        echo "# Optional: remove # to debug"
        echo "# debug ipc"
    } > "$gpg_agent_config"
    
    chmod 600 "$gpg_agent_config"
    log_info "Configuration written to $gpg_agent_config"
}

# Restart GPG agent
restart_gpg_agent() {
    log_info "Restarting GPG agent..."
    
    # Kill existing agent
    gpgconf --kill gpg-agent 2>/dev/null || :
    sleep 1
    
    # Start new agent
    if gpg-connect-agent --quiet /bye >/dev/null 2>&1; then
        log_info "GPG agent restarted successfully"
        return 0
    else
        log_error "Failed to start GPG agent"
        return 1
    fi
}

# Test the configuration
test_configuration() {
    log_info "Testing GPG configuration..."
    
    # Test 1: Check agent is running
    if ! gpg-connect-agent 'GETINFO version' /bye >/dev/null 2>&1; then
        log_error "GPG agent is not responding"
        return 1
    fi
    log_info "GPG agent is running"
    
    # Test 2: Attempt a simple signing operation
    # This will trigger pinentry if cache is empty
    if echo "test" | gpg --clearsign -o /dev/null 2>/dev/null; then
        log_info "Successfully signed a test message"
        return 0
    else
        log_warn "Could not sign test message (expected if this is first run)"
        log_warn "Try again after entering your GPG passphrase in the GUI dialog"
        return 0
    fi
}

# Show verification checklist
show_checklist() {
    cat >&2 <<'EOF'

Verification Checklist:
  ✓ Pinentry program found and executable
  ✓ GPG agent configuration file created
  ✓ Configuration permissions set (600)
  ✓ GPG agent restarted
  ✓ DISPLAY or WAYLAND_DISPLAY is set
  ✓ Basic signing test passed

Next steps:
  1. Try a commit: git commit --allow-empty -m "test"
     (Should open GUI dialog for password, not block terminal)
  
  2. Verify Pi integration:
     cd /home/random_user/.config
     pi  # Launch Pi, try to commit
  
  3. Troubleshoot if needed:
     - Check gpg-agent is running: gpg-connect-agent /bye
     - View config: cat ~/.gnupg/gpg-agent.conf
     - See agent log: tail -f ~/.cache/gpg-agent.log

EOF
}

main() {
    local pinentry_prog="${1:---auto}"
    
    case "$pinentry_prog" in
        --help|-h)
            usage
            exit 0
            ;;
        --auto)
            log_info "Auto-detecting pinentry program..."
            pinentry_prog=$(find_pinentry)
            if [[ -z "$pinentry_prog" ]]; then
                log_error "No pinentry program found"
                log_error "Install the pinentry package for your distribution:"
                log_error "  Arch:   sudo pacman -S pinentry"
                log_error "  Debian: sudo apt install pinentry-gnome3"
                log_error "  Fedora: sudo dnf install pinentry-gtk"
                log_error "If gnome3/qt frontends are present but fail to run,"
                log_error "install their shared-library dependencies, e.g. on"
                log_error "Arch: sudo pacman -S gcr kwindowsystem"
                exit 1
            fi
            log_info "Auto-detected: $pinentry_prog"
            ;;
        --gtk2)
            pinentry_prog="pinentry-gtk2"
            ;;
        --gnome3)
            pinentry_prog="pinentry-gnome3"
            ;;
        --qt)
            pinentry_prog="pinentry-qt"
            ;;
        --kde)
            pinentry_prog="pinentry-kde"
            ;;
        *)
            log_error "Unknown option: $pinentry_prog"
            usage
            exit 1
            ;;
    esac
    
    # Get full path
    local pinentry_path
    pinentry_path=$(get_pinentry_path "$pinentry_prog")
    
    if [[ -z "$pinentry_path" ]]; then
        log_error "Pinentry not found: $pinentry_prog"
        log_error "Install it with your package manager"
        exit 1
    fi
    
    # Verify it's actually executable
    if ! check_pinentry_installed "$pinentry_path"; then
        exit 1
    fi
    
    log_info "Found: $pinentry_path"
    
    # Check for GUI support (warning only, don't fail)
    check_gui_support || true
    
    # Configure GPG agent
    configure_gpg_agent "$pinentry_path"
    
    # Restart agent
    if ! restart_gpg_agent; then
        exit 1
    fi
    
    # Run tests
    log_info "Running configuration tests..."
    if test_configuration; then
        log_info "Configuration successful!"
        show_checklist
        exit 0
    else
        log_warn "Tests completed with warnings"
        show_checklist
        exit 0
    fi
}

main "$@"
